cas/config/routes.rb
Rails.application.routes.draw do
  resources :timeslots
  resources :courses
  resources :rooms
  root to: 'pages#root'
  
  get 'admin_main', to: 'pages#admin_main'
  get 'assignment_table', to:'pages#assignment_table'
  
  resources :users
  get 'change_role', to: 'users#change_role'
  post 'change_role', to: 'users#update'
  get 'assignment_by_faculty', to:'users#assignment_by_faculty'
  get 'execute_reset_faculty_preferences', to: 'users#execute_reset_faculty_preferences'
  
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'get_current_semester', to:'systemvariables#get_current_semester'
  get 'set_current_semester', to:'systemvariables#set_current_semester'
  
  get 'new_day', to:'systemvariables#new_day'
  get 'create_day', to:'systemvariables#create_day'
  get 'delete_day', to:'systemvariables#delete_day'
  get 'new_time', to:'systemvariables#new_time'
  get 'create_time', to:'systemvariables#create_time'
  get 'delete_time', to:'systemvariables#delete_time'
  get 'faculty_edit_permission', to:'systemvariables#faculty_edit_permission'
  get 'set_faculty_permission', to:'systemvariables#set_faculty_permission'
  #get 'unacceptable_time_slot_limit', to:'systemvariables#unacceptable_time_slot_limit'
  #get 'set_unacceptable_limit', to:'systemvariables#set_unacceptable_limit'
  #get 'preferred_time_slot_limit', to:'systemvariables#preferred_slot_limit'
  #get 'set_preferred_limit', to:'systemvariables#set_preferred_limit'
  get 'preference_limits', to:'systemvariables#preference_limits'
  get 'set_preference_limits', to: 'systemvariables#set_preference_limits'
  
  get 'new_time_table', to:'timeslots#new_time_table'
  get 'time_table', to:'timeslots#show_time_table'
  get 'anm_table', to:'timeslots#anm_table'
  
  get 'set_preference', to:'timeslot_users#set_preference'
  get 'reset_faculty_preference', to:'users#reset_faculty_preference'
  
  get 'get_course_repo', to:'courses#get_course_repo'
  get 'add_to_current_courses', to:'courses#add_to_current_courses'
  get 'copy_courses', to: 'courses#copy_courses'
  get 'delete_course_repo', to:'courses#delete_course_repo'
  get 'delete_all_courses', to:'courses#delete_all_courses'
  get 'enough_rooms', to:'courses#enough_rooms'
  get 'auto_schedule', to:'courses#auto_schedule'
end

cas/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy, :schedule_course]
  before_action :require_admin
  before_action :set_courses, only: [:index, :update, :assign_room, :set_course_time, :delete_all_courses, :auto_schedule]
  before_action :render_edit, only: [:edit, :update]
  
  helper_method :room_availability, :get_option

  # GET /courses
  # GET /courses.json
  #############################################################################
  def index
  end

  # GET /courses/1
  # GET /courses/1.json
  #############################################################################
  def show
    if (@course.time!=nil)
      if(!@course.time.strip.empty?)
        @timelines = parse_available_time(@course.time)
      end
    end
  end

  # GET /courses/new
  #############################################################################
  def new
    @course = Course.new
    @course_repo = Course.where("year=?",0).order(:number)
  end

  # GET /courses/1/edit
  #############################################################################
  def edit
  end

  # POST /courses
  # POST /courses.json
  #############################################################################
  def create
    @course = Course.new(course_params)
    @course.year = 0
    @course.room_id = 1
    @course.user_id = 1

    if @course.save
      flash[:success] = 'Course was successfully added.'
      redirect_to new_course_path
    else
      render :new
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  #############################################################################
  def update
    keep_field_values
    #check if user entered time is legit format
    if (course_params[:time]!=nil)
      if(!course_params[:time].strip.empty?)
        @timelines = parse_available_time(course_params[:time])
      end
    end
    
    user = User.find(course_params[:user_id])
    if(@timelines!=nil)
      room = Room.find(course_params[:room_id])
      if room.capacity < course_params[:size].to_i
        flash.now[:danger] = "Course size is set to greater than the room capacity."
        render :edit
        return
      end
      radct = room_available_during_course_time?(room, course_params[:time], @courses, @course)
      fto = faculty_time_overlap?
      if(radct && !fto)
        if @course.update(course_params)
          flash[:success] = 'Course was successfully updated.'
          redirect_to edit_course_path(@course)
        else
          render :edit 
          return
        end
      else
        if !radct
          flash.now[:danger] = "#{room.number} is not available during this class time"
          render :edit
          return
        end
        if fto
          flash.now[:danger] = "#{user.full_name} has another class scheduled at this time"
          render :edit
          return
        end
      end
    else
      render :edit 
      return
    end
  end
  
  #############################################################################
  def room_available_during_course_time?(room, new_course_time, courses, current_course)
    ct = parse_available_time(new_course_time)
    
    if room.id==1
      return true
    end
    if room.available_time==nil
      flash[:danger] = "Available time for #{room.number} is not set"
      return false
    else
      if room.available_time.empty?
        flash[:danger] = "Available time for #{room.number} is not set"
        return false
      end
    end
    #room_available_time = parse_available_time(room.available_time)
    room_available_time = room_availability(room, courses, current_course)
    room_available_time.each do |t|
      if include_time?(t, ct[0])
        return true
      end
    end
    return false
  end
  
  #############################################################################
  def faculty_time_overlap?
    user_id = course_params[:user_id].to_i
    user = User.find(user_id)
    if user_id==1
      return false
    end
    faculty_courses = user.courses.where(year: current_year, semester: current_semester )
    faculty_courses.each do |fc|
      f_time = fc.time.split('-')
      c_time = course_params[:time].split('-')
      if(@course.id != fc.id)
        if(f_time[0][0]==c_time[0][0] && f_time[1]==c_time[1])
          return true
        end
      end
    end
    return false
  end
  
  #############################################################################
  def room_availability(room, courses, current_course)
    if (room.available_time==nil || room.id==1)
      return nil
    end
    if room.available_time.empty?
      return nil
    end
    ra = parse_available_time(room.available_time)
    courses.each do |course|
      ct = course.time
      if(course.room_id==room.id && course.id!=current_course.id)
        if ct!=nil
          if !ct.empty?
            ra = subtract_time_group(ra,parse_available_time(ct))
          end
        end
      end
    end
    return ra
  end
  
  #############################################################################  
  def copy_courses
    previous_year = params[:previous_year]
    previous_semester = params[:previous_semester]
    courses = Course.where(:year=>previous_year, :semester=>previous_semester)
    if courses!=nil
      if !courses.empty?
        courses.each do |course|
          Course.create(:number=>course.number, :name=>course.name, :size=>course.size, 
                        :time=>course.time, :year=>current_year, :semester=>current_semester,
                        :room_id=>course.room_id, :user_id=>course.user_id)
        end
        flash[:success] = "Courses from #{previous_year} #{previous_semester} are successfully copied."
      else
        flash[:danger] = "#{previous_year} #{previous_semester} does not have courses."
      end
    else
      flash[:danger] = "#{previous_year} #{previous_semester} does not have courses."
    end
    
    redirect_to get_course_repo_path
  end
  
  # DELETE /courses/1
  # DELETE /courses/1.json
  #############################################################################
  def destroy
    @course.destroy
    flash[:success] = "#{@course.number} was successfully deleted."
    redirect_to :back
  end
  
  #############################################################################
  def delete_course_repo
    @course = Course.find(params[:id])
    @course.destroy
    flash[:success] = "#{@course.number} was successfully deleted."
    redirect_to new_course_path
  end
  
  #############################################################################
  def delete_all_courses
    @courses.each do |course|
      course.destroy
    end
    flash[:success] = "All current semester courses are deleted."
    redirect_to get_course_repo_path
  end
  
  #############################################################################
  def get_course_repo
    @course_repo = Course.where("year=?",0).order(:number)
    @current_courses = set_courses
    @year = Systemvariable.find_by(:name =>"scheduling_year")
    @semester = Course.where.not(:year=>0).pluck(:semester).uniq
  end
  
  #############################################################################
  def add_to_current_courses
    @course_repo = Course.where("year=?",0).order(:number)
    origin_course = Course.find(params[:id])
    
    @course = Course.new
    @course.number = origin_course.number
    @course.name = origin_course.name
    @course.size = 0
    @course.year = Systemvariable.find_by(:name=> "scheduling_year").value.to_i
    @course.semester = Systemvariable.find_by(:name=> "scheduling_semester").value
    @course.room_id = 1
    @course.user_id = 1

    if @course.save
      flash[:success] = "#{@course.number} was successfully added."
      redirect_to get_course_repo_path
    else
      render :get_course_repo
    end
  end
  
  #############################################################################
  def enough_rooms
    @rooms = Room.all.order(capacity: :desc)
    @courses = Course.where(year: current_year, semester: current_semester ).order(:size=> :desc)
    @timeslots = Timeslot.all
    room_timeslots = []  #[100,100,100,50,50,50,50,30] means that there are 
                          # three timelots with room capacity of 100, and so on.
                          # In descent order of capacity.
    @rooms.each do |room|
      mw = [0,0]
      tr = [0,0]
      if room.id ==1
        next
      end
      rats = room.available_time
      arr_rat = parse_available_time(rats)
      arr_rat.each do |rt|
        @timeslots.each do |ts|
          arr_ts = timeslot_to_array_time(ts)
          if include_time?(rt, arr_ts)
            if ts.from_time < 1700
              room_timeslots << room.capacity
            else
              if ts.day == "MW"
                mw[0] += 1
              elsif ts.day =="M" || ts.day=="W"
                mw[1] += 1
              elsif ts.day =="TR"
                tr[0] += 1
              elsif ts.day == "T" || ts.day == "R"
                tr[1] += 1
              end
            end
          end
        end
        max_mw = (mw[0] > mw[1]) ? mw[0] : mw[1]
        max_tr = (tr[0] > tr[1]) ? tr[0] : tr[1]
        for i in 1..max_mw
          room_timeslots << room.capacity
        end
        for i in 1..max_tr
          room_timeslots << room.capacity
        end
      end
    end
    
    @courses_no_room = []
    @courses_size_not_set = []
    @courses.each do |course|
      if course.size == 0
        @courses_size_not_set << course
        next
      end
      if course.size <= room_timeslots[0]
        room_timeslots.delete_at(0)
        next
      else
        @courses_no_room << course
      end
    end
    
    if @courses_no_room.empty? && @courses_size_not_set.empty?
      flash[:success] = "Rooms are enough."
      redirect_to courses_path
    elsif !@courses_no_room.empty?
      flash.now[:danger] = "NOT enough rooms."

cas/app/helpers/courses_helper.rb
module CoursesHelper
end

cas/app/views/courses/_content.html.erb
<% @rooms.each do |room| %>
  <% course = get_course(room, mtwrf) %>
  <% preference = get_faculty_preference(mtwrf) %>
  <% availability = get_availability(room, mtwrf) %>
  
  <% if availability==false %>
    <td bgcolor="#AAAAAA">
  <% else %>
    <% if course==nil || course.user_id == @course.user_id%>
      <% if preference == 1 %> 
        <td bgcolor="#CCFFCC"> 
      <% elsif preference == 3 %> 
        <td bgcolor="#FFCCCC"> 
      <% else %>
        <td>
      <% end %>
    <% else %> 
      <td> 
    <% end %>
  <% end %>
    
  <% if course != nil %>     
    <% if room.id != 1 %>  
      <% @assigned_courses << course %>
    <% end %>
    <%= link_to course.number, edit_course_path(course) %> 
    <% if course.user_id!=1 %>
      <%= course.user.full_name %>
    <% end %>
    <br>size: <%= course.size %>
  <% end %>
  </td>
<% end %>

cas/app/views/courses/_faculty_preferences.html.erb
<!-- faculty preference  -->
<tr>
  <td>
    <% if @course.user_id!=1 %>
      <h4><%= @course.user.full_name %> preference</h4>
      <div class='row'>
        <div class="col-xs-9">
          <table class="table table-striped">
            <% @days.each do |day| %>
              <tr>
                <td><b><%= day %></b></td>
                <% @timeslots.each do |ts| %>
                  <% if day == ts.day %>
                    <% option = get_option(ts) %>
                    <% if option[0]==1 %>
                      <td  bgcolor="#CCFFCC"> <%= format_time(ts.from_time.to_s+"-"+ts.to_time.to_s) %> </td>
                    <%elsif option[0] == 3%> 
                      <td  bgcolor="#FFCCCC"> <%= format_time(ts.from_time.to_s+"-"+ts.to_time.to_s) %> </td>
                    <% end %>
                  <% end %>
                <% end %>
              </tr>
            <% end %>
        </table>
        </div>
      </div>
    <% end %>
  </td>
</tr>

cas/app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <div>
    <table>
      <tr>
        <td><%= f.label :section, :style => "float:left; margin-right: 1em;" %></td>
        <td><%= f.text_field :section %></td>
      </tr>
      <tr>
        <td><%= f.label :size, :style => "float:left; margin-right: 1em;" %></td>
        <td><%= f.number_field :size %></td>
      </tr>
      <tr>
        <td><%= f.label "Faculty", :style => "float:left; margin-right: 1em;" %></td>
        <td><%= f.select :user_id, options_for_select(@users, course.user_id) %></td>
      </tr>
      <tr>
        <td><%= f.label :room_id, :style => "float:left; margin-right: 1em;" %></td>
        <td><%= f.select :room_id, options_for_select(@rooms_select, course.room_id) %></td>
      </tr>
      <tr>
        <td><%= f.label :time, :style => "float:left; margin-right: 1em;" %></td>
        <td><%= f.select :time, options_for_select(@stringtimeslots, course.time) %></td>
      </tr>
    </table>
  </div>

  <div class="actions">
    <%= f.submit class:'btn btn-default' %>
  </div>
<% end %>

cas/app/views/courses/auto_schedule.html.erb
<%=@test%>

cas/app/views/courses/edit.html.erb
<table>
  <tr>
    <td valign="top">
      <h4><%= @course.number %>-<%= @course.section %> <%= @course.name %></h4>
      <%= render 'form', course: @course %>
      <br><br>
    </td>
    <td width="100"></td>
    <td valign="top">
      <table>
        <!-- room availability in table -->
        <tr>
          <td>
            <h4>Available Rooms</h4>
            <%= render './pages/timetable' %>
          </td>
        </tr>
        
        <!-- room availability in numbers -->
        <tr>
          <td>
            <h4>Room Availability</h4>
            <div class='row'>
              <div class="col-xs-9">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Number</th>
                      <th>Capacity</th>
                      <th>Available time</th>
                    </tr>
                  </thead>
                
                  <tbody>
                    <% @rooms.each do |room| %>
                      <% if room.capacity >= @course.size %>
                        <tr>
                          <td><b><%= room.id %></b></td>
                          <td><%= room.number %></td>
                          <td><%= room.capacity %></td>
                          <td>
                            <% ra = room_availability(room, @courses, @course) %>
                            <% if ra!=nil %>
                              <%= format_day_time(ra)%>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

cas/app/views/courses/enough_rooms.html.erb
<div class="row">
  <div class="col-sm-6">
    <% if @courses_no_room.count >0 %>
    <h4> Need room for:</h4>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Number</th>
            <th>Size</th>
            <th>Name</th>
          </tr>
        </thead>
        <tbody>
          <% @courses_no_room.each do |c| %>
            <tr>
              <td> <%= c.number %> </td>
              <td> <%= c.size %> </td>
              <td> <%= c.name %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>
<br><br>

<div class="row">
  <div class="col-sm-6">
    <% if @courses_size_not_set.count >0 %>
      <h4> Not checked for:</h4>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Number</th>
            <th>Size</th>
            <th>Name</th>
          </tr>
        </thead>
        <tbody>
          <% @courses_size_not_set.each do |c| %>
            <tr>
              <td> <%= link_to c.number, edit_course_path(c) %> </td>
              <td> <%= c.size %> </td>
              <td> <%= c.name %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

cas/app/views/courses/get_course_repo.html.erb
<h4>Copy courses from previous semesters semester</h4>

<div class='row'>
  <div class="col-sm-9">
    <%= form_tag("/copy_courses", method: "get") do %>
      <div class="field">
        <%= number_field_tag(:previous_year, @year.value.to_i, :style => "float:left;  margin-right: 1em;") %>
        <%= select_tag :previous_semester, options_for_select(@semester), :style => "float:left; margin-right: 1em; " %>
        <%= submit_tag "Copy", data: { confirm: "Are you sure to copy all the courses?" }, class:'btn btn-sm btn-default', :style => "float:left; margin-right: 1em;" %>
      </div>
    <% end %>
  </div>
</div>
<br><br><br><br>

<h4>Courses for current semester</h4>
<div class='row'>
  <div class="col-sm-9">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Number</th>
          <th>Name</th>
          <th>Semester</th>
          <th colspan="2"><%= link_to 'Delete All', delete_all_courses_path, data: { confirm: "Are you sure to delete all classes?" }, class:'btn btn-small btn-danger' %></th>
        </tr>
      </thead>
    
      <tbody>
        <% if !@current_courses.empty? %>
          <% @current_courses.each do |course| %>
            <tr>
              <td><%= course.number %></td>
              <td><%= course.name %></td>
              <td><%= course.year %> <%= course.semester %></td>
              <td><%= link_to 'Add', add_to_current_courses_path(:id=>course.id), class:'btn btn-sm btn-default' %></td>
              <td><%= link_to 'Delete', course, method: :delete, data: { confirm: "Are you sure to delete #{course.number}?" }, class:'btn btn-sm btn-default' %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<br><br><br><br>
<h4>Course repository</h4>

<div class='row'>
  <div class="col-sm-9">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Number</th>
          <th>Name</th>
          <th>Add</th>
        </tr>
      </thead>
    
      <tbody>
        <% if !@course_repo.empty? %>
          <% @course_repo.each do |course| %>
            <tr>
              <td><%= course.number %></td>
              <td><%= course.name %></td>
              <td><%= link_to 'Add', add_to_current_courses_path(:id=>course.id), class:'btn btn-sm btn-info' %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

cas/app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-sm-12">
  <table>
    <tr>
      <td><%= link_to 'Add Course', get_course_repo_path, class:'btn btn-default' %></td>
      <td><%= link_to 'Enough Rooms?', enough_rooms_path, class:'btn btn-default' %> </td>
      <td> <%= link_to 'Schedule Unassigned Courses', auto_schedule_path(:auto_schedule=>"remaining"), class:'btn btn-default' %> </td>
      <td><%= link_to 'Schedule All Courses', auto_schedule_path(:auto_schedule=>"all"), data: { confirm: '!!! IMPORTANT: Are you sure to re-schedule ALL the courses?' }, class:'btn btn-danger btn-default' %> </td>
    </tr>
  </table>
</div>

<div class='row'>
  <div class="col-sm-12">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Number</th>
          <th>Section</th>
          <th>Name</th>
          <th>Size</th>
          <th>Time</th>
          <th>Semester</th>
          <th>Room</th>
          <th>Faculty</th>
          <th colspan="2">Actions</th>
        </tr>
      </thead>
    
      <tbody>
        <% if !@courses.empty? %>
          <% @courses.each do |course| %>
            <tr>
              <td><%= course.number %></td>
              <td><%= course.section %></td>
              <td><%= course.name %></td>
              <td><%= course.size if course.size!=0 %></td>
              <td>
                <% if course.time!=nil && course.room_id != 1%> 
                  <% if !course.time.empty? %>
                    <%= day_time_display(course.time) %>
                  <% end %>
                <% end %>
              </td>
              <td><%= course.year %> <%= course.semester %></td>
              <td><% if course.room_id!=1 %><%= course.room.number %><% end %></td>
              <td><%= course.user.full_name if course.user.id !=1%></td>
              <td><%= link_to 'Schedule/Edit', edit_course_path(course), class:'btn btn-sm btn-default'  %></td>
              <td><%= link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-sm btn-default'  %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<div class='row'>
  <div class="col-xs-2">
  </div>
</div>

cas/app/views/courses/new.html.erb
<h4>Add New Course to Course Repository</h4>

<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Number *" %>
    <%= f.text_field :number %>
  </div>


  <div class="field">
    <%= f.label "Name *" %>
    <%= f.text_field :name %>
  </div>
  
  <div class="actions">
    <%= f.submit "Add Class", class:'btn btn-default' %>
  </div>
<% end %>

<%= link_to 'Back', courses_path %>

<br><br><br><br>
<h4>Current course repository</h4>

<div class='row'>
  <div class="col-sm-9">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Number</th>
          <th>Name</th>
          <th>Delete</th>
        </tr>
      </thead>
    
      <tbody>
        <% if !@course_repo.empty? %>
          <% @course_repo.each do |course| %>
            <tr>
              <td><%= course.number %></td>
              <td><%= course.name %></td>
              <td><%= link_to 'Delete', delete_course_repo_path(:id=>course.id), data: { confirm: 'Are you sure?' }, class:'btn btn-sm btn-default' %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

cas/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @course.number %>
</p>

<p>
  <strong>Section:</strong>
  <%= @course.section %>
</p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @course.size %>
</p>

<p>
  <strong>Day:</strong>
  <%= @course.day %>
</p>

<p>
  <strong>Time:</strong>
  <%= @course.time %>
</p>

<p>
  <strong>Year:</strong>
  <%= @course.year %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @course.semester %>
</p>

<p>
  <strong>Room:</strong>
  <%= @course.room_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @course.user_id %>
</p>

<%= link_to 'Edit', edit_course_path(@course), class:'btn btn-default' %> |