cas/config/routes.rb
Rails.application.routes.draw do
  resources :timeslots
  resources :courses
  resources :rooms
  root to: 'pages#root'
  
  get 'admin_main', to: 'pages#admin_main'
  get 'assignment_table', to:'pages#assignment_table'
  
  resources :users
  get 'change_role', to: 'users#change_role'
  post 'change_role', to: 'users#update'
  get 'assignment_by_faculty', to:'users#assignment_by_faculty'
  get 'execute_reset_faculty_preferences', to: 'users#execute_reset_faculty_preferences'
  
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'get_current_semester', to:'systemvariables#get_current_semester'
  get 'set_current_semester', to:'systemvariables#set_current_semester'
  
  get 'new_day', to:'systemvariables#new_day'
  get 'create_day', to:'systemvariables#create_day'
  get 'delete_day', to:'systemvariables#delete_day'
  get 'new_time', to:'systemvariables#new_time'
  get 'create_time', to:'systemvariables#create_time'
  get 'delete_time', to:'systemvariables#delete_time'
  get 'faculty_edit_permission', to:'systemvariables#faculty_edit_permission'
  get 'set_faculty_permission', to:'systemvariables#set_faculty_permission'
  #get 'unacceptable_time_slot_limit', to:'systemvariables#unacceptable_time_slot_limit'
  #get 'set_unacceptable_limit', to:'systemvariables#set_unacceptable_limit'
  #get 'preferred_time_slot_limit', to:'systemvariables#preferred_slot_limit'
  #get 'set_preferred_limit', to:'systemvariables#set_preferred_limit'
  get 'preference_limits', to:'systemvariables#preference_limits'
  get 'set_preference_limits', to: 'systemvariables#set_preference_limits'
  
  get 'new_time_table', to:'timeslots#new_time_table'
  get 'time_table', to:'timeslots#show_time_table'
  get 'anm_table', to:'timeslots#anm_table'
  
  get 'set_preference', to:'timeslot_users#set_preference'
  get 'reset_faculty_preference', to:'users#reset_faculty_preference'
  
  get 'get_course_repo', to:'courses#get_course_repo'
  get 'add_to_current_courses', to:'courses#add_to_current_courses'
  get 'copy_courses', to: 'courses#copy_courses'
  get 'delete_course_repo', to:'courses#delete_course_repo'
  get 'delete_all_courses', to:'courses#delete_all_courses'
  get 'enough_rooms', to:'courses#enough_rooms'
  get 'auto_schedule', to:'courses#auto_schedule'
end

cas/app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-sm-9 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

cas/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'COURSE ASSIGNING SYSTEM', root_path, class: "navbar-brand", id: "log" %>
    </div>
    
    <% if logged_in?%>
      <% if current_user.is_admin %>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Faculty List', users_path %></li>
            <li><%= link_to 'Room List', rooms_path %></li>
            <li><%= link_to 'Course List', courses_path %></li>
            <li><%= link_to 'View Time Table', assignment_table_path, class: 'btn btn-default' %></li>
            <li><%= link_to "Scheduling for: #{current_year} #{current_semester}", get_current_semester_path%></li>
          </ul>
        <% end %>
      <% end %>
      
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Logout', logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign up', new_user_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

cas/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cas</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container col-lg-8 col-lg-offset-1">
      <%= yield %>
    </div>
    
  </body>
</html>