cas/config/routes.rb
Rails.application.routes.draw do
  resources :timeslots
  resources :courses
  resources :rooms
  root to: 'pages#root'
  
  get 'admin_main', to: 'pages#admin_main'
  get 'assignment_table', to:'pages#assignment_table'
  
  resources :users
  get 'change_role', to: 'users#change_role'
  post 'change_role', to: 'users#update'
  get 'assignment_by_faculty', to:'users#assignment_by_faculty'
  get 'execute_reset_faculty_preferences', to: 'users#execute_reset_faculty_preferences'
  
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'get_current_semester', to:'systemvariables#get_current_semester'
  get 'set_current_semester', to:'systemvariables#set_current_semester'
  
  get 'new_day', to:'systemvariables#new_day'
  get 'create_day', to:'systemvariables#create_day'
  get 'delete_day', to:'systemvariables#delete_day'
  get 'new_time', to:'systemvariables#new_time'
  get 'create_time', to:'systemvariables#create_time'
  get 'delete_time', to:'systemvariables#delete_time'
  get 'faculty_edit_permission', to:'systemvariables#faculty_edit_permission'
  get 'set_faculty_permission', to:'systemvariables#set_faculty_permission'
  #get 'unacceptable_time_slot_limit', to:'systemvariables#unacceptable_time_slot_limit'
  #get 'set_unacceptable_limit', to:'systemvariables#set_unacceptable_limit'
  #get 'preferred_time_slot_limit', to:'systemvariables#preferred_slot_limit'
  #get 'set_preferred_limit', to:'systemvariables#set_preferred_limit'
  get 'preference_limits', to:'systemvariables#preference_limits'
  get 'set_preference_limits', to: 'systemvariables#set_preference_limits'
  
  get 'new_time_table', to:'timeslots#new_time_table'
  get 'time_table', to:'timeslots#show_time_table'
  get 'anm_table', to:'timeslots#anm_table'
  
  get 'set_preference', to:'timeslot_users#set_preference'
  get 'reset_faculty_preference', to:'users#reset_faculty_preference'
  
  get 'get_course_repo', to:'courses#get_course_repo'
  get 'add_to_current_courses', to:'courses#add_to_current_courses'
  get 'copy_courses', to: 'courses#copy_courses'
  get 'delete_course_repo', to:'courses#delete_course_repo'
  get 'delete_all_courses', to:'courses#delete_all_courses'
  get 'enough_rooms', to:'courses#enough_rooms'
  get 'auto_schedule', to:'courses#auto_schedule'
end

cas/app/views/pages/_content.html.erb
<% @rooms.each do |room| %>
  <% course = get_course(room, mtwrf) %>
  <% preference = get_preference(course, mtwrf) %>
  <% availability = get_availability(room, mtwrf) %>
  
  <% if availability==false %>
    <td bgcolor="#AAAAAA">
  <% else %>
    <% if course != nil %> 
      <% if preference == 1 %> 
        <td bgcolor="#CCFFCC"> 
      <% elsif preference == 3 %> 
        <td bgcolor="#FFCCCC"> 
      <% else %> 
        <td> 
      <% end %>
      
      <% if room.id != 1%>  
        <% @assigned_courses << course %>
      <% end %>
      <%= link_to course.number, edit_course_path(course) %> 
      <% if course.user_id!=1 %>
        <%= course.user.full_name %>
      <% end %>
      <br>size: <%= course.size %>
    
    <% else %>
      <td>
    <% end %>
  <% end %>
  </td>
<% end %>

cas/app/views/pages/_timetable.html.erb
<div class='row'>
  <div class="col-lg-12">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="150"></th>
          <% @rooms.each do |room| %>
            <th> <%= room.number %> [<%= room.capacity %>] </th> 
          <% end %>
        </tr>
      </thead>
    
      <tbody>
        <% @timeslots.each do |ts| %>
          <tr>
            <td><%= ts.day %> <%= format_time(ts.from_time.to_s+"-"+ts.to_time.to_s) %></td>
            <%= render 'content', mtwrf: ts %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

cas/app/views/pages/admin_main.html.erb
<br><br>
<div class="row" >
  <div class="col-sm-3">
    <dl>
      <dt align="center">Resources</dt>
      <dd vspcae="30"><%= link_to 'Add faculty', new_user_path, class:'btn btn-sm btn-default btn-block' %></dd>
      <dd><%= link_to 'Add room', new_room_path, class:'btn btn-sm btn-default  btn-block'  %></dd>
      <dd><%= link_to 'Add course', get_course_repo_path, class:'btn btn-sm btn-default  btn-block'  %></dd>
      <dd><%= link_to 'Course repository',  new_course_path, class:'btn btn-sm btn-default  btn-block' %></dd>
    </dl>
  </div>
  <div class="col-sm-3">
    <dl align="center">
      <dt>Schedule Courses</dt>
      <dd><%= link_to 'Schedule courses', courses_path, class:'btn btn-sm btn-default btn-block'  %></dd>
      <dd><%= link_to 'View by faculty', assignment_by_faculty_path, class:'btn btn-sm btn-default btn-block'  %></dd>
    </dl>
  </div>

  <div class="col-sm-3">
    <dl align="center">
      <dt>Faculty Preference Settings</dt>
      <dd><%= link_to "Set faculty edit permission", faculty_edit_permission_path, class:'btn btn-sm btn-default btn-block'  %></dd>
      <dd><%= link_to "Reset faculty preferences", reset_faculty_preference_path, class:'btn btn-sm btn-default btn-block'  %></dd>
      <dd><%= link_to 'Set preference limits', preference_limits_path, class:'btn btn-sm btn-default btn-block'  %></dd>
    </dl>
  </div>
</div>

cas/app/views/pages/assignment_table.html.erb
<h3>Course Assignments Table</h3>
<%= render 'timetable' %>

<div class='row'>
  <div class="col-xs-9">
    <h3>Not Assigned Room </h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Actions</th>
          <th>Number</th>
          <th>Section</th>
          <th>Name</th>
          <th>Size</th>
          <th>Time</th>
          <th>Faculty</th>
        </tr>
      </thead>
    
      <tbody>
        <% unassigned_courses = get_unassigned_courses %>
        <% if !unassigned_courses.empty? %>
          <% unassigned_courses.each do |course| %>
            <tr>
              <td><%= link_to 'Assign', edit_course_path(course), class: 'btn btn-sm btn-default' %></td>
              <td><%= course.number %></td>
              <td><%= course.section %></td>
              <td><%= course.name %></td>
              <td><%= course.size %></td>
              <td>
                <% if course.time!=nil %> 
                  <% if !course.time.empty? %>
                    <%= day_time_display(course.time) %>
                  <% end %>
                <% end %>
              </td>
              <td><%= course.user.full_name if course.user.id !=1%></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>