cas/config/routes.rb
Rails.application.routes.draw do
  resources :timeslots
  resources :courses
  resources :rooms
  root to: 'pages#root'
  
  get 'admin_main', to: 'pages#admin_main'
  get 'assignment_table', to:'pages#assignment_table'
  
  resources :users
  get 'change_role', to: 'users#change_role'
  post 'change_role', to: 'users#update'
  get 'assignment_by_faculty', to:'users#assignment_by_faculty'
  get 'execute_reset_faculty_preferences', to: 'users#execute_reset_faculty_preferences'
  
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'get_current_semester', to:'systemvariables#get_current_semester'
  get 'set_current_semester', to:'systemvariables#set_current_semester'
  
  get 'new_day', to:'systemvariables#new_day'
  get 'create_day', to:'systemvariables#create_day'
  get 'delete_day', to:'systemvariables#delete_day'
  get 'new_time', to:'systemvariables#new_time'
  get 'create_time', to:'systemvariables#create_time'
  get 'delete_time', to:'systemvariables#delete_time'
  get 'faculty_edit_permission', to:'systemvariables#faculty_edit_permission'
  get 'set_faculty_permission', to:'systemvariables#set_faculty_permission'
  #get 'unacceptable_time_slot_limit', to:'systemvariables#unacceptable_time_slot_limit'
  #get 'set_unacceptable_limit', to:'systemvariables#set_unacceptable_limit'
  #get 'preferred_time_slot_limit', to:'systemvariables#preferred_slot_limit'
  #get 'set_preferred_limit', to:'systemvariables#set_preferred_limit'
  get 'preference_limits', to:'systemvariables#preference_limits'
  get 'set_preference_limits', to: 'systemvariables#set_preference_limits'
  
  get 'new_time_table', to:'timeslots#new_time_table'
  get 'time_table', to:'timeslots#show_time_table'
  get 'anm_table', to:'timeslots#anm_table'
  
  get 'set_preference', to:'timeslot_users#set_preference'
  get 'reset_faculty_preference', to:'users#reset_faculty_preference'
  
  get 'get_course_repo', to:'courses#get_course_repo'
  get 'add_to_current_courses', to:'courses#add_to_current_courses'
  get 'copy_courses', to: 'courses#copy_courses'
  get 'delete_course_repo', to:'courses#delete_course_repo'
  get 'delete_all_courses', to:'courses#delete_all_courses'
  get 'enough_rooms', to:'courses#enough_rooms'
  get 'auto_schedule', to:'courses#auto_schedule'
end

cas/app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :timeslot_users, dependent: :destroy
  has_many :timeslots, through: :timeslot_users
  
  before_save { self.email = email.downcase}
  
  validates :first_name, presence: true, length: { minimum: 2, maximum: 25 }
  validates :last_name, presence: true, length: { minimum: 2, maximum: 25 }
  validates :full_name, uniqueness: { case_sensitive: false }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  
  has_secure_password
end

cas/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :change_role, :get_option]
  before_action :require_same_user, only: [:show, :edit, :update]
  before_action :require_admin, except:[:show, :edit,:update]
  helper_method :get_option
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all.order(:last_name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    #general code
    ############################################################################
    # @days = Systemvariable.where("name=?","day")
    # @times = Systemvariable.where("name=?", "time")
    # #@days = Systemvariable.where(:name =>"day")
    # #@times = Systemvariable.where(:name =>"time")
    # @faculty_permission = Systemvariable.find_by(:name=>"enable_faculty_edit?")
    # @unacceptable_time_slot_limit = Systemvariable.find_by(:name=>"unacceptable_time_slot_limit")
    # @preferred_time_slot_limit =  Systemvariable.find_by(:name=>"preferred_time_slot_limit")
    # @timeslot_current_user = TimeslotUser.where("user_id=?", @user.id).includes(:timeslot)
    # #@timeslot_current_user = TimeslotUser.where(:user_id=>@user.id).includes(:timeslot)
    
    
    # if !@timeslot_current_user.empty?
    #   count=0
    #   order_matched_hash = {}
    #   @times.each do |t|
    #     ft = t.value.split('-')[0].to_i
    #     tt = t.value.split('-')[1].to_i
    #     @days.each do |d|
    #       @timeslot_current_user.each do |tcu|
    #         if(d.value == tcu.timeslot.day && ft==tcu.timeslot.from_time && tt == tcu.timeslot.to_time)
    #           order_matched_hash[count] = tcu.preference_type
    #           count += 1
    #         end
    #       end
    #     end
    #   end
      
    #   index = 0
    #   @preferences = []
    #   @times.each do |t|
    #     row = []
    #     @days.each do |d|
    #       row << order_matched_hash[index]
    #       index += 1
    #     end
    #     @preferences << row
    #   end
    # end
    #############################################################################
    
    #A&M CS code
    @faculty_permission = Systemvariable.find_by(:name=>"enable_faculty_edit?")
    @unacceptable_time_slot_limit = Systemvariable.find_by(:name=>"unacceptable_time_slot_limit")
    @preferred_time_slot_limit =  Systemvariable.find_by(:name=>"preferred_time_slot_limit")
    @user_pref = TimeslotUser.where("user_id=?", @user.id).includes(:timeslot)
    @timeslots = Timeslot.all
    @days = Timeslot.pluck(:day).uniq
    @courses = @user.courses
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.full_name = @user.last_name + ", " + @user.first_name
    if @user.save
      create_preferences
      flash[:success] = 'Faculty successfully added.'
      redirect_to users_path
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      @user.full_name = @user.last_name + ", " + @user.first_name
      @user.update(user_params)
      if !current_user.is_admin
        redirect_to user_path(@user)
      else
      flash[:success] = "#{@user.full_name} was successfully updated."
        redirect_to users_path
      end
    else
      flash.now[:danger] = "Failed to add faculty."
      render :edit
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @courses = Course.all
    @courses.each do |course|
      if(course.user_id == @user.id)
        course.user_id = 1
        course.save
      end
    end
    @user.destroy
    flash[:success] = "#{@user.full_name}  was successfully deleted."
    redirect_to users_url
  end
  
  def change_role
  end
  
  def assignment_by_faculty
    @users = User.all
  end
  

  def get_option(mw)
    @user_pref.each do |up|
      if (up.timeslot.day == mw.day && up.timeslot.from_time == mw.from_time)
        option = "A"
        color = ""
        if(up.preference_type==1)
          color = "#CCFFCC"
          option = "P"
        elsif (up.preference_type==3)
          color = "#FFCCCC"
          option = "U"
        end
        return [up.preference_type,color,option]
      end
    end
  end
  
  def reset_faculty_preference
    
  end
  
  def execute_reset_faculty_preferences
    timeslot_user = TimeslotUser.all
    timeslot_user.each do |tu|
      tu.destroy
    end
    redirect_to root_path
    flash[:success] = "All faculty preferences are reset to default."
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :full_name, :is_admin, :email, :password)
    end
    
    def require_same_user 
      if current_user != @user and !current_user.is_admin?
        flash[:danger] = "You have no permission to visit this page."
        redirect_to root_path
      end
    end
    
    def create_preferences
      #default preferences
      timeslots =Timeslot.all
      timeslots.each do |ts|
        pt = (ts.from_time>=1700) ? 3 : 2
        TimeslotUser.create(:user_id=>@user.id, :timeslot_id=>ts.id, :preference_type=>pt)
      end
    end
end

cas/app/helpers/users_helper.rb
module UsersHelper
end

cas/app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class='row'>
  <div class="col-sm-8">
    <%= form_for(@user, :html =>{class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :first_name %>
        </div>
        <div class="col-sm-4">
          <%= f.text_field :first_name, class: "form-control", placeholder: "Enter your first name", autofocus: true %>
        </div>
      </div>
    
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :last_name %>
        </div>
        <div class="col-sm-4">
          <%= f.text_field :last_name, class: "form-control", placeholder: "Enter your last name", autofocus: true %>
        </div>
      </div>
    
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-4">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter your email", autofocus: true %>
        </div>
      </div>
    
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password%>
        </div>
        <div class="col-sm-4">
          <%= f.password_field :password, class: "form-control", autocomplete: false%>
        </div>
      </div>
    
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
          <%= f.submit class: 'btn btn-default'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

cas/app/views/users/_role_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
  </div>

  <div class="field">
    <%= f.label :is_admin %>
    <%= f.check_box :is_admin %>
  </div>

  <div class="actions">
    <%= f.submit 'Change role', class:'btn btn-default' %>
  </div>
<% end %>

cas/app/views/users/assignment_by_faculty.html.erb
<div class='row'>
  <div class="col-sm-6">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>First name</th>
          <th>Last name</th>
          <th>Courses</th>
        </tr>
      </thead>
    
      <tbody>
        <% if !@users.empty? %>
          <% @users.each do |user| %>
            <% if user.id!=1 %>
              <tr>
                <td><%= user.first_name %></td>
                <td><%= user.last_name %></td>
                <td>
                  <% user.courses.each do |course| %>
                    <% if course.year == current_year.to_i && course.semester==current_semester %>
                      <%= course.number %> | 
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </table>
</div>
</div>

cas/app/views/users/change_role.html.erb
<h1>Change user role</h1>

<%= render 'role_form', user: @user %>

cas/app/views/users/edit.html.erb
<div class="col-xs-offset-3 col-xs-9">
  <h3>Edit Info</h3>
</div>

<%= render 'form', user: @user %>

cas/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div>
  <%= link_to 'Add faculty', new_user_path, class: 'btn btn-default' %>
</div><br>

<div class='row'>
  <div class="col-sm-8">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Last name</th>
          <th>First name</th>
          <th>Is admin</th>
          <th>Email</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>
    
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.last_name %></td>
            <td><%= user.first_name %></td>
            <td><%= 'Yes' if user.is_admin%></td>
            <td><%= user.email %></td>
            <td><%= link_to 'Show', user, class:'btn btn-sm btn-default'  %></td>
            <td><%= link_to 'Reset password', edit_user_path(user), class:'btn btn-sm btn-default'  %></td>
            <% if current_user.id != user.id && user.id != 1 %>
              <td><%= link_to 'Change role', change_role_path(:id => user.id), class:'btn btn-sm btn-default'  %></td>
              <td><%= link_to 'Delete', user, method: :delete, data: { confirm: "Are you sure to delete #{user.first_name} #{user.last_name}?" }, class:'btn btn-sm btn-default'  %></td>
            <% else %>
              <td></td><td></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>
</div>

cas/app/views/users/new.html.erb
<div class='row'>
  <div class="col-sm-6">
    <h3 align="center">Add Faculty</h3>
  </div>
</div>

<%= render 'form', user: @user %>

cas/app/views/users/reset_faculty_preference.html.erb
<br><br>
<div>
  <td><%= link_to "Reset all faculty preferences",execute_reset_faculty_preferences_path, 
                  data: { confirm: "Are you sure to reset all faculty preferences?"}, class: 'btn btn-lg btn-danger' %></td>
</div>

cas/app/views/users/show-general.html.erb
<h3 align="center"><%= @user.full_name %></h3>
<div align="center">
  <%= link_to 'Edit profile', edit_user_path(@user), class: 'btn btn-default btn-sm'%>
</div><br><br>

<%= form_tag("/set_preference", method: "get") do %>
  <%= hidden_field_tag :id, @user.id %>
  <div class="well col-xs-8 col-xs-offset-1">
    <h5><b>P</b>:preferred  <b>A</b>:acceptable  <b>U</b>:unacceptable</h5>
    <h5>Maximum "unacceptable" time slots: <b><%= @unacceptable_time_slot_limit.value%></b></h5>
    <h5>Maximum "preferred" time slots: <b><%= @preferred_time_slot_limit.value%></b></h5>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="120px"> </th>
          <% @days.each do |day| %>
            <th  width="100px"> <%= day.value %> </th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% if @timeslot_current_user.empty? %>
          <% @times.each do |time| %>
            <tr>
              <td><%= format_time(time.value) %><br></td>
              <% @days.each do |day| %>
                <% if @faculty_permission.value=="yes" %>
                  <td><%= select_tag("prf-#{day.value}-#{time.value}".to_sym, options_for_select([['P',1], ['A',2], ['U', 3]], 2)) %> </td>
                <% else %>
                  <td>A</td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
        <% else %>
          <% row_index = 0 %>
          <% @times.each do |time| %>
            <tr>
              <td><%= format_time(time.value) %><br></td>
              <% pref_current_row =  pref_current_row = @preferences[row_index] %>
              <% row_index = row_index + 1 %>
              <% col_index = 0 %>
              <% @days.each do |day| %>
                <% if pref_current_row[col_index] ==1 %> <td bgcolor="#CCFFCC"> <% end %> <% if pref_current_row[col_index] ==2 %> <td> <% end %> <% if pref_current_row[col_index] ==3 %> <td bgcolor="#FFCCCC"> <% end %>
                <% if @faculty_permission.value=="yes" %>
                  <%= select_tag("prf-#{day.value}-#{time.value}".to_sym, options_for_select([['P',1], ['A',2], ['U', 3]], pref_current_row[col_index])) %> </td>
                <% else %>
                  <% if pref_current_row[col_index] ==1 %> P <% end %> <% if pref_current_row[col_index] ==2 %> A <% end %> <% if pref_current_row[col_index] ==3 %> U <% end %></td>
                <% end %>
                <% col_index = col_index + 1 %>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <% if @faculty_permission.value=="yes" %>
      <%= submit_tag("Update preferences", class: 'btn btn-default' )%>
    <% else %>
      <%= submit_tag("View Only", disabled: true, class: 'btn btn-default' )%> 
    <% end %>
  </div>
<% end %>

cas/app/views/users/show.html.erb
<h3 align="center"><%= @user.full_name %></h3>
<div align="center">
  <%= link_to 'Edit profile', edit_user_path(@user), class: 'btn btn-default btn-sm'%>
</div><br><br>

<div class="col-xs-7 col-xs-offset-1">
  <% if !@courses.empty? %>
    <h4>Assigned courses:</h4>
    <table class="table table-striped">
      <th>Number</th>
      <th>Name</th>
      <th>Section</th>
      <th>Size</th>
      <th>Room</th>
      <th>Time</th>
      <% @courses.each do |course| %>
        <% if course.year == current_year.to_i && course.semester==current_semester %>
          <tr>
            <td><%= course.number %></td>
            <td><%= course.name %></td>
            <td><%= course.section %></td>
            <td><%= course.size %></td>
            <td><%= course.room.number %></td>
            <td>
              <% if course.time!=nil %> 
                <% if !course.time.empty? %>
                  <%= day_time_display(course.time) %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
  <% end %>
</div>


<%= form_tag("/set_preference", method: "get") do %>
  <%= hidden_field_tag :id, @user.id %>
  <div class="col-xs-7 col-xs-offset-1">
    <br><br>
    <p>
      <% if @faculty_permission.value=="yes" %>
        <%= submit_tag("Update preferences", class: 'btn btn-primary' )%>
      <% else %>
        <%= submit_tag("View Only", disabled: true, class: 'btn btn-default' )%> 
      <% end %>
    </p>
    <b>P</b>:preferred  <b>A</b>:acceptable  <b>U</b>:unacceptable <br>
    Maximum "preferred" time slots: <b><%= @preferred_time_slot_limit.value%></b> <br>
    Maximum "unacceptable" time slots: <b><%= @unacceptable_time_slot_limit.value%></b> <br><br>
      <table class="table table-striped">
          <% @days.each do |day| %>
            <tr>
              <td><b><%= day %></b></td>
              <% @timeslots.each do |ts| %>
                <% if day == ts.day %>
                  <% option = get_option(ts) %>
                  <td  bgcolor="<%=option[1]%>" >
                    <% if @faculty_permission.value=="yes" %>
                      <%= format_time(ts.from_time.to_s+"-"+ts.to_time.to_s) %>
                      <%= select_tag("prf-#{day}-#{ts.from_time}-#{ts.to_time}".to_sym, options_for_select([['P',1], ['A',2], ['U', 3]], option[0])) %>
                    <% else %>
                      <%= format_time(ts.from_time.to_s+"-"+ts.to_time.to_s) %> <br>
                      <%= option[2] %>
                    <% end %>
                  </td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
      </table>

  </div>
<% end %>

<div class="col-xs-7 col-xs-offset-1">
  <hr>
  Developed by <b>Chengde Wu</b> 2016
  <br><br><br><br>
</div>